- hosts: localhost
  vars:
    source_key: './.ssh/id_rsa'
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    home: "{{ lookup('env', 'HOME') }}/"
  pre_tasks:
    - name: brew Cache
      community.general.homebrew:
        update_homebrew: true
      tags:
        - node
        - zsh
  tasks:
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/node-setup.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/dotfiles.yml
