- name: Installing stow
  community.general.homebrew: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: 'cd ./dotfiles && zsh ./setup && stow  */ --target={{ home | dirname }}'
