- name: make sure .ssh directory exists.
  file:
    dest: '{{ dest_key | dirname }}'
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key
  copy:
    src: '{{ source_key }}'
    dest: '{{ dest_key }}'
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key public
  copy:
    src: '{{ source_key }}.pub'
    dest: '{{ dest_key }}.pub'
  tags:
    - dotfiles
    - install
    - ssh
