- name: Install ZSH
  apt: name=zsh
  tags: zsh
- name: install oh my zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags: zsh
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags: zsh
